[package]
name = "duid-dev"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
duid = { path = "../../", features = ["default"] }
wasm-bindgen = "0.2"


[profile.release]
debug = true